import { Geist, Geist_Mono, Play } from "next/font/google"; // ✅ Import Play font
import { MantineProvider } from "@mantine/core"; // ✅ Import Mantine
import "@mantine/core/styles.css"; // ✅ Ensure Mantine styles are loaded
import "./globals.css";
import Nav from "@/app/components/nav"; // Import Navbar
import BottomNav from "@/app/components/bottomNav";
import "@mantine/dates/styles.css";

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

const play = Play({
  subsets: ["latin"],
  weight: ["400", "700"], // ✅ Specify font weights
  variable: "--font-play",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${play.variable}`}
    >
      <body className="antialiased">
        <MantineProvider withGlobalStyles withNormalizeCSS>
          <Nav />

          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
